ALTER TABLE hero_banners
    ADD COLUMN title_color VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
    ADD COLUMN subtitle_color VARCHAR(20) NOT NULL DEFAULT '#E2E8F0',
    ADD COLUMN description_color VARCHAR(20) NOT NULL DEFAULT '#F8FAFC';
